version: '3'

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    volumes:
      - /home/xavier/dev/data/pg_data:/var/lib/postgresql/data
      - /home/xavier/dev/data/pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - /home/xavier/dev/mundial2018/mundial2018:/opt/mundial2018
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    command: uwsgi --ini /opt/mundial2018/uwsgi.ini

volumes:
  pg_data: {}
  pg_backups: {}
