# Generated by Django 2.0 on 2018-03-23 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('bandera', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Estadi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('ciutat', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagat', models.BooleanField(default=False)),
                ('posicio', models.SmallIntegerField()),
                ('posicio_anterior', models.SmallIntegerField()),
                ('punts', models.SmallIntegerField(default=0)),
                ('punts_anterior', models.SmallIntegerField(default=0)),
                ('punts_resultats', models.PositiveSmallIntegerField(default=0)),
                ('punts_grups', models.PositiveSmallIntegerField(default=0)),
                ('punts_equips_encertats', models.PositiveSmallIntegerField(default=0)),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaihora', models.DateTimeField()),
                ('gols1', models.SmallIntegerField(default=-1)),
                ('gols2', models.SmallIntegerField(default=-1)),
                ('empat', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('equip1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip1', to='joc.Equip')),
                ('equip2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip2', to='joc.Equip')),
                ('estadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Estadi')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Grup')),
            ],
        ),
        migrations.CreateModel(
            name='PronosticEquipGrup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicio', models.PositiveSmallIntegerField(default=0)),
                ('punts', models.PositiveSmallIntegerField(default=0)),
                ('diferencia', models.SmallIntegerField(default=0)),
                ('favor', models.PositiveSmallIntegerField(default=0)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Equip')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PronosticPartit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols1', models.SmallIntegerField(default=-1)),
                ('gols2', models.SmallIntegerField(default=-1)),
                ('empat', models.PositiveSmallIntegerField(null=True)),
                ('equip1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip1_pronostic', to='joc.Equip')),
                ('equip2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip2_pronostic', to='joc.Equip')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Jugador')),
                ('partit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Partit')),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joc.Grup'),
        ),
    ]
